-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

NDefines.NGame.START_DATE = "546.1.1"
NDefines.NGame.END_DATE = "100000.1.1"
NDefines.NGame.MAX_RANDOM_NEW_WORLD = "100000.1.1"

NDefines.NReligion.ASPECT_ADD_COST = 100
NDefines.NReligion.ASPECT_REMOVE_COST = 0
NDefines.NReligion.MAX_UNLOCKED_ASPECTS = 3
NDefines.NReligion.CHURCH_POWER_RATE_SCALE = 0.1

NDefines.NReligion.KARMA_FOR_OFFENSIVE_WAR = 10
NDefines.NReligion.KARMA_FOR_DEFENSIVE_WAR = -10
NDefines.NReligion.KARMA_FOR_HONORING_CTA = 0
NDefines.NReligion.KARMA_PER_RELEASED_PROVINCE = -1
NDefines.NReligion.KARMA_PER_TAKEN_PROVINCE = 1
NDefines.NReligion.KARMA_TOO_HIGH = 50
NDefines.NReligion.KARMA_TOO_LOW = -50
NDefines.NReligion.KARMA_JUST_RIGHT_HIGH = 25
NDefines.NReligion.KARMA_JUST_RIGHT_LOW = -25
NDefines.NReligion.KARMA_RESTORE_ON_RULER_DEATH = 0

NDefines.NReligion.CHANGE_SECONDARY_PRESTIGE_HIT = -50

NDefines.NFrontend.FRONTEND_POS_X = 4050.0
NDefines.NFrontend.FRONTEND_LOOK_X = 4050.0
NDefines.NFrontend.CAMERA_START_X = 4050.0
NDefines.NFrontend.CAMERA_END_X = 4050.0
NDefines.NFrontend.CAMERA_LOOKAT_X = 4050.0

NDefines.NDiplomacy.CALL_TO_ARMS_COST = 0

NDefines.NCountry.CORE_LOSE = -1								-- how many years until a core is lost.
NDefines.NCountry.CORE_LOSE_CULTURE_GROUP = -1

NDefines.NAI.AI_USES_HISTORICAL_IDEA_GROUPS = 0

NDefines.NCountry.MAX_IDEA_GROUPS_FROM_SAME_CATEGORY = 1
NDefines.NCountry.EXPLORE_COAST_EVENT_CHANCE = 10
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_1 = 392
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_2 = 407
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_3 = 99
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_4 = 80
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_5 = 166
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_6 = 224

NDefines.NCountry.WESTERNISATION_THRESHOLD = 100